apps/blog/urls.py
from django.urls import path
from . import views


app_name = "blog"

urlpatterns = [
    path("", views.HomePageView.as_view(), name="home"),
    path("about/", views.AboutPageView.as_view(), name="about"),
    path("contacts/", views.ContactsPageView.as_view(), name="contacts"),
    path("delete/<slug:slug>", views.PostDeletePageView.as_view(), name="post_delete"),
    path("<slug:slug>", views.PostDetailPageView.as_view(), name="post_detail"),
    path("update/<slug:slug>", views.PostUpdateView.as_view(), name="post_update"),
    path("create/", views.PostCreatePageView.as_view(), name="post_create"),
    path("user/posts/", views.UserPostsPageView.as_view(), name="user_posts"),
    path("like/<slug:slug>", views.post_like, name="post_like"),
    path("dislike/<slug:slug>", views.post_dislike, name="post_dislike"),
    path("message/<slug:slug>", views.post_message, name="post_message"),
    path("settings/", views.SettingsPageView.as_view(), name="user_settings"),
]

apps/users/urls.py
from django.urls import path

from . import views


app_name = "users"

urlpatterns = [
    path("login/", views.LoginPageView.as_view(), name="login"),
    path("register/", views.RegisterPageView.as_view(), name="register"),
    path("logout/", views.LogoutPageView.as_view(), name="logout"),
    path(
        "profile/<str:username>",
        views.UserProfilePageView.as_view(),
        name="user_profile",
    ),
]

core/urls.py
from django.conf.urls import handler400, handler403, handler404, handler500  # noqa
from django.conf.urls.i18n import i18n_patterns  # noqa: F401
from django.conf.urls.static import static
from django.conf import settings

from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.sitemaps.views import sitemap

from apps.blog.sitemaps import PostSitemap
from apps.users.api_endpoints import router as users_api_router
from apps.blog.api_endpoints import router as blog_api_router

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)


sitemaps = {
    "posts": PostSitemap,
}

# URLs
urlpatterns = [
    path("admin/", admin.site.urls),
    path("i18n", include("django.conf.urls.i18n")),
    path("rosetta/", include("rosetta.urls")),
]

# Translated urls
urlpatterns += i18n_patterns(
    path("", include("apps.blog.urls", namespace="blog")),
    path("users/", include("apps.users.urls", namespace="users")),
    path("robots.txt", TemplateView.as_view(template_name="bunin/robots.txt")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
)

# API Endpoints
urlpatterns += [
    path("api/token", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("api/token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("api/v1/users/", include(users_api_router.urls)),
    path("api/v1/blogs/", include(blog_api_router.urls)),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler400 = "apps.shared.views.bad_request_view"  # noqa
handler403 = "apps.shared.views.page_permission_denied_view"  # noqa
handler404 = "apps.shared.views.page_not_found_view"  # noqa
handler500 = "apps.shared.views.server_error_view"  # noqa

apps/blog/forms.py
from django import forms

from apps.users.models import User, UserProfile
from .models import Post


default_attrs = lambda name, placeholder: {  # noqa :E731
    "name": name,
    "placeholder": placeholder,
    "class": "form-control",
}


class PostCreateUpdateForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ("title", "description", "content", "status")

        widgets = {
            "title": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "name": "title",
                    "placeholder": "Enter you`r post title...",
                }
            ),
            "description": forms.Textarea(
                attrs={
                    "class": "form-control",
                    "name": "description",
                    "placeholder": "Enter you`r post description...",
                }
            ),
            "content": forms.Textarea(
                attrs={
                    "class": "form-control",
                    "name": "content",
                    "placeholder": "Enter you`r post content...",
                }
            ),
            "status": forms.Select(
                attrs={
                    "class": "form-select",
                    "name": "status",
                    "placeholder": "Enter you`r post status...",
                }
            ),
        }


class SettingsUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ("first_name", "last_name", "email")

    first_name = forms.CharField(
        widget=forms.TextInput(
            attrs=default_attrs("first_name", "First name..."),
        ),
        required=False,
    )
    last_name = forms.CharField(
        widget=forms.TextInput(
            attrs=default_attrs("last_name", "Last name"),
        ),
        required=False,
    )
    email = forms.EmailField(
        widget=forms.EmailInput(attrs=default_attrs("email", "Email..."))
    )


class SettingsUserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ("avatar", "bio")

    avatar = forms.ImageField(
        widget=forms.FileInput(attrs=default_attrs("avatar", "Avatar..."))
    )
    bio = forms.CharField(widget=forms.TextInput(attrs=default_attrs("bio", "Bio...")))

apps/blog/api_endpoints/blog/Post/views.py
from rest_framework import viewsets, permissions

from apps.blog.models import Post
from .serializer import PostSerializer


class PostViewSet(viewsets.ModelViewSet):
    queryset = Post.published.all().order_by("-created_at")
    serializer_class = PostSerializer

    def get_permissions(self):
        if self.action in ["list", "retrieve"]:
            return [permissions.AllowAny()]
        return [permissions.IsAuthenticated()]


__all__ = ("PostViewSet",)

apps/blog/api_endpoints/blog/PostComment/views.py
from rest_framework import viewsets, permissions

from apps.blog.models import PostComment
from .serializers import PostCommentSerializer


class PostCommentViewSet(viewsets.ModelViewSet):
    queryset = PostComment.objects.all().order_by("-created_at")
    serializer_class = PostCommentSerializer

    def get_permissions(self):
        if self.action in ["list", "retrieve"]:
            return [permissions.AllowAny()]
        return [permissions.IsAuthenticated()]


__all__ = ("PostCommentViewSet",)

apps/blog/api_endpoints/blog/PostCommentLike/views.py
from rest_framework import viewsets, permissions

from apps.blog.models import PostCommentLike
from .serializers import PostCommentLikeSerializer


class PostCommentLikeViewSet(viewsets.ModelViewSet):
    queryset = PostCommentLike.objects.all().order_by("-id")
    serializer_class = PostCommentLikeSerializer
    permission_classes = [permissions.IsAuthenticated]


__all__ = ("PostCommentLikeViewSet",)

apps/blog/api_endpoints/blog/PostDislike/views.py
from django.shortcuts import get_object_or_404

from rest_framework import viewsets, response, status, permissions

from apps.blog.models import PostDislike, PostLike, Post
from .serializers import PostDislikeSerializer


class PostDislikeViewSet(viewsets.ModelViewSet):
    queryset = PostDislike.objects.all()
    serializer_class = PostDislikeSerializer
    permission_classes = [permissions.IsAuthenticated]

    def create(self, request, *args, **kwargs):
        post_id = request.data.get("post")
        post = get_object_or_404(Post, id=post_id)
        user = request.user

        PostLike.objects.filter(post=post, user=user).delete()

        existing_dislike = PostDislike.objects.filter(post=post, user=user)
        if existing_dislike.exists():
            existing_dislike.delete()
            return response.Response(
                {"message": "Dislike removed"}, status=status.HTTP_200_OK
            )

        dislike = PostDislike.objects.create(post=post, user=user)
        serializer = self.get_serializer(dislike)

        return response.Response(serializer.data, status=status.HTTP_201_CREATED)


__all__ = ("PostDislikeViewSet",)

apps/blog/api_endpoints/blog/PostLike/views.py
from django.shortcuts import get_object_or_404

from rest_framework import viewsets, response, status, permissions

from apps.blog.models import PostLike, PostDislike, Post
from .serializers import PostLikeSerializer


class PostLikeViewSet(viewsets.ModelViewSet):
    queryset = PostLike.objects.all()
    serializer_class = PostLikeSerializer
    permission_classes = [permissions.IsAuthenticated]

    def create(self, request, *args, **kwargs):
        post_id = request.data.get("post")
        post = get_object_or_404(Post, id=post_id)
        user = request.user

        PostDislike.objects.filter(post=post, user=user).delete()

        existing_like = PostLike.objects.filter(post=post, user=user)
        if existing_like.exists():
            existing_like.delete()
            return response.Response(
                {"message": "Like removed"}, status=status.HTTP_200_OK
            )

        like = PostLike.objects.create(post=post, user=user)
        serializer = self.get_serializer(like)

        return response.Response(serializer.data, status=status.HTTP_201_CREATED)


__all__ = ("PostLikeViewSet",)

apps/blog/views.py
import datetime

from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView, DeleteView
from django.contrib import messages
from django.views import View
from django.urls import reverse

from apps.users.models import User
from apps.shared.mixins import CustomHtmxMixin
from .models import Post
from .forms import (
    PostCreateUpdateForm,
    SettingsUserForm,
    SettingsUserProfileForm,
)
from .utils import (
    get_search_model_queryset,
    get_pagination_obj,
    set_post_like,
    set_post_dislike,
    set_post_comment,
)


class HomePageView(CustomHtmxMixin, TemplateView):
    template_name = "blog/home.html"

    def get_context_data(self, **kwargs):
        if self.request.user is not None and self.request.user.is_authenticated:
            posts = Post.published.exclude(author=self.request.user)
        else:
            posts = Post.published.all()

        search_query = self.request.GET.get("search_query", None)
        page = self.request.GET.get("page", 1)
        size = self.request.GET.get("size", 4)

        posts = get_search_model_queryset(posts, search_query)

        page_obj = get_pagination_obj(posts, page, size)

        kwargs["title"] = "Home"
        kwargs["page_obj"] = page_obj
        kwargs["size_value"] = size
        kwargs["search_query_value"] = search_query

        return super().get_context_data(**kwargs)


class AboutPageView(CustomHtmxMixin, TemplateView):
    template_name = "blog/about.html"

    def get_context_data(self, **kwargs):
        kwargs["title"] = "About"
        return super().get_context_data(**kwargs)


class ContactsPageView(CustomHtmxMixin, TemplateView):
    template_name = "blog/contacts.html"

    def get_context_data(self, **kwargs):
        kwargs["title"] = "Contacts"
        return super().get_context_data(**kwargs)


class PostDetailPageView(CustomHtmxMixin, View):
    template_name = "blog/post_detail.html"

    def get(self, request, slug):
        post = get_object_or_404(Post, slug=slug)

        post_comments = post.post_comments.all().order_by("-created_at")
        post.watching += 1
        post.save()

        context = {
            "title": post.title,
            "post": post,
            "post_comments": post_comments,
            "template_htmx": self.template_htmx,
        }

        return render(request, self.template_name, context)


class PostCreatePageView(CustomHtmxMixin, LoginRequiredMixin, TemplateView):
    template_name = "blog/post_create.html"

    def get_context_data(self, **kwargs):
        kwargs["form"] = PostCreateUpdateForm()
        kwargs["title"] = "Post Create"
        return super().get_context_data(**kwargs)

    def post(self, request):
        form = PostCreateUpdateForm(request.POST)

        if form.is_valid():
            cd = form.cleaned_data
            post = Post.objects.create(
                title=cd.get("title"),
                status=cd.get("status"),
                description=cd.get("description"),
                content=cd.get("content"),
                author=request.user,
                publisher_at=datetime.datetime.now().strftime("%Y-%m-%d"),
            )
            post.save()

            messages.success(request, "Post succesfully created")
            return redirect("blog:home")

        messages.warning(
            request,
            "There is a mistake in your post ! or your post is not filled to the depth.",
        )
        return redirect(reverse("blog:post_create"))


class PostUpdateView(CustomHtmxMixin, LoginRequiredMixin, TemplateView):
    template_name = "blog/post_update.html"

    def get(self, request, slug):
        post = get_object_or_404(Post, slug=slug, is_active=True)

        form = PostCreateUpdateForm(instance=post)
        context = {
            "title": "Update " + post.title,
            "template_htmx": self.template_htmx,
            "form": form,
            "post": post,
        }
        return render(request, self.template_name, context)

    def post(self, request, slug):
        post = get_object_or_404(Post, slug=slug)
        form = PostCreateUpdateForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            messages.success(request, "Post succsessfully updated")
            return redirect(reverse("blog:post_update", kwargs={"slug": slug}))

        messages.error(request, "You`r post is not valid !")
        return redirect(reverse("blog:post_update", kwargs={"slug": slug}))


class UserPostsPageView(CustomHtmxMixin, LoginRequiredMixin, TemplateView):
    template_name = "blog/user_posts.html"

    def get(self, request):

        search_query_for_user_posts = request.GET.get(
            "search_query_for_user_posts", None
        )
        posts = Post.objects.filter(author=request.user, is_active=True)

        if search_query_for_user_posts is not None:
            posts = get_search_model_queryset(posts, search_query_for_user_posts)

        context = {
            "title": "My posts",
            "template_htmx": self.template_htmx,
            "posts": posts.order_by("-created_at"),
        }
        return render(request, self.template_name, context)


class PostDeletePageView(CustomHtmxMixin, LoginRequiredMixin, DeleteView):
    template_name = "blog/post_confirm_delete.html"
    model = Post

    def post(self, request, slug):
        post = get_object_or_404(Post, slug=slug)
        post.delete()
        messages.success(request, "post successfully deleted")
        return redirect("blog:user_posts")


class SettingsPageView(CustomHtmxMixin, LoginRequiredMixin, View):
    template_name = "blog/settings.html"

    def get(self, request):
        user = get_object_or_404(User, pk=request.user.pk)
        user_form = SettingsUserForm(instance=user)
        user_profile_form = SettingsUserProfileForm(instance=user.profiles)
        context = {
            "title": "Settings",
            "template_htmx": self.template_htmx,
            "user_form": user_form,
            "user_profile_form": user_profile_form,
        }

        return render(request, self.template_name, context)

    def post(self, request):
        print(request.FILES)
        print(request.POST)

        user = get_object_or_404(User, pk=request.user.pk)
        user_form = SettingsUserForm(data=request.POST, instance=user)
        user_profile_form = SettingsUserProfileForm(
            data=request.POST, files=request.FILES, instance=user.profiles
        )
        if user_form.is_valid() and user_profile_form.is_valid():
            user_form.save()
            user_profile_form.save()

            messages.success(request, "Successfully updated profile settings.")
            return redirect(reverse("blog:user_settings"))

        messages.error(request, "Invalid parametres.")
        return redirect(reverse("blog:user_settings"))


def post_like(request, slug):
    if not request.user.is_authenticated:
        return redirect(reverse("users:login"))
    set_post_like(request.user, slug)
    return redirect(reverse("blog:post_detail", kwargs={"slug": slug}))


def post_dislike(request, slug):
    if not request.user.is_authenticated:
        return redirect(reverse("users:login"))
    set_post_dislike(request.user, slug)
    return redirect(reverse("blog:post_detail", kwargs={"slug": slug}))


def post_message(request, slug):
    if not request.user.is_authenticated:
        return redirect(reverse("users:login"))

    post_message_input = request.GET.get("post_message_input", None)

    if post_message_input is not None:
        set_post_comment(request.user, slug, post_message_input)
    return redirect(reverse("blog:post_detail", kwargs={"slug": slug}))

templates/blog/contacts.html
<main role="main" class="container">
    <div class="row">
        <div class="col-md-8">
            <!-- Content -->
             Contact content
        </div>
        {% include 'components/latest_posts.html' %}
    </div>
</main>

templates/blog/home.html
{% load blog_tags %}
<main role="main" class="container" id="main-content">
  <div class="row">
    <div class="col-md-8">
        {% for massage in massages %}
          <div class="alert alert-{{ message.tags }}">
            <h6>{{ massage }}</h6>
          </div>
        {% endfor %}
        
        
        {% for post in page_obj.object_list %}
        <div class="col-md-12">
          
          <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
            <div class="col p-4 d-flex flex-column position-static">
              
              <div class="d-flex">
                <strong class="d-inline-block mb-2">
                  <a 
                  href="{% url 'users:user_profile' post.author.username %}" 
                  hx-get="{% url 'users:user_profile' post.author.username %}" 
                  hx-push-url="true"
                  hx-target="#main-content"
                  class="nav-link">
                      <img src="{{ post.get_author_avatar_url }}" style="border-radius: 30%;" width="30px" height="30px" alt="author logo">
                    {{ post.author }}
                  </a>
                </strong>
                <!-- <strong class="d-inline-block mb-2 col text-primary"><i class="bi bi-watch">{{ post.watching }}</i></strong>
                <strong class="d-inline-block mb-2 col text-primary"><i class="bi bi-star">{{ post.like_count }}</i></strong>
                <strong class="d-inline-block mb-2 col text-primary"><i class="bi bi-chat">{{ post.comment_count }}</i></strong> -->
              </div>
              <h3 class="mb-0">{{ post.title }}</h3>
              <div class="mb-1 text-muted">{{ post.publisher_at }}</div>
              <p class="card-text mb-auto">{{ post.description|truncatewords_html:30 }}</p>
              <a 
              href="{{ post.get_absolute_url }}" 
              hx-get="{{ post.get_absolute_url }}" 
              hx-push-url="true"
              hx-target="#main-content"
              class="stretched-link">Continue reading</a>
              <div class="d-flex">
                <strong class="d-inline-block mb-2 col text-primary"><i class="bi bi-eye">{{ post.watching }}</i></strong>
                <strong class="d-inline-block mb-2 col text-primary"><i class="bi bi-star">{{ post.like_count }}</i></strong>
                <strong class="d-inline-block mb-2 col text-primary"><i class="bi bi-chat">{{ post.comment_count }}</i></strong>
            </div>
            </div>
          </div>
        </div>
        {% empty %}
        <div align="center">
          <h3>Post not found</h3>
        </div>

        {% endfor %}
    </div>
    {% include 'components/latest_posts.html' %}
  </div>
  {% include 'components/paginators.html' %}
</main>

templates/blog/post_confirm_delete.html

<main role="main" class="container">
    <div class="row">
    <div class="col-md-8">
            <div class="content-section">
                <form method="POST" action="{% url 'blog:post_delete' post.slug %}">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4"><h4><b>You are deleted post:</b></h4></legend>
                        <h4>"{{ post.title }}" ?</h4>
                    </fieldset>
                    <div class="form-group">
                        <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                        <a 
                        class="btn btn-outline-secondary" 
                        href="{{ post.get_absolute_url }}#content"
                        hx-get="{{ post.get_absolute_url }}#content"
                        hx-push-url="true"
                        hx-target="#main-content"
                        >Cancel</a>
                    </div>
                </form>
            </div>
        </div>
        {% include 'components/latest_posts.html' %}
        </div>
        </main>
            
            

templates/blog/post_detail.html
{% load static blog_tags %}

<main role="main" class="container" id="content">
  <div class="row">
    <div class="col-md-8">
      <article class="blog-post">
        <h2 class="blog-post-title">{{ post.title }}</h2>
        <p class="blog-post-meta">{{ post.publisher_at }}by 
          <a 
          href="{% url 'users:user_profile' post.author.username %}"
          hx-get="{% url 'users:user_profile' post.author.username %}"
          hx-push-url="true"
          hx-target="#main-content"
          >{{ post.author }}</a>
        </p>
        
        <div class="text">
          <p><small>{{ post.description }}</small></p>
        </div>
        <!-- Content -->
        <p>{{ post.content|markdown|safe }}</p>

      </article>
      <hr>
      <div class="d-flex mt-3 mb-3" id="post_counts">

        <!-- Watching count-->
        <div class="mb-2">
          <a 
          href="#main-content" 
          hx-get="#main-content" 
          hx-push-url="true"
          hx-target="#main-content"
          class="nav-link text-dark">
            <i class="bi bi-eye">({{ post.watching }})</i>
          </a>
        </div>
        <!-- Comments count -->
        <div class="mb-2">
          <a 
          href="#post_comments" 
          hx-get="#post_comments" 
          hx-push-url="true"
          hx-target="#main-content"
          class="nav-link text-dark">
            <i class="bi bi-chat-left-text">({{ post.comment_count }})</i>
          </a>
        </div>
        <!-- Like count -->
        <div class="md-2" id="post_like_count">
          <a 
          href="{% url 'blog:post_like' post.slug %}#post_like_count" 
          hx-get="{% url 'blog:post_like' post.slug %}#post_like_count"
          hx-push-url="true"
          hx-target="#main-content" 
          class="nav-link text-dark">
            {% if request.user.is_authenticated %}
              {% if post|check_like:request.user %}
                <i class="bi bi-star-fill">({{ post.like_count }})</i>
              {% else %}
                <i class="bi bi-star">({{ post.like_count }})</i>
              {% endif %}
            {% else %}
                <i class="bi bi-star">({{ post.like_count }})</i>
            {% endif %}
          </a>
        </div>
        <!-- Dislike count -->
        <div class="md-2" id="post_dislike_count">
          <a 
          href="{% url 'blog:post_dislike' post.slug %}#post_dislike_count" 
          hx-get="{% url 'blog:post_dislike' post.slug %}#post_dislike_count" 
          hx-push-url="true"
          hx-target="#main-content"
          class="nav-link text-dark">
            {% if request.user.is_authenticated %}
              {% if post|check_dislike:request.user %}
                <i class="bi bi-emoji-frown-fill">({{ post.dislike_count }})</i>
              {% else %}
                <i class="bi bi-emoji-frown">({{ post.dislike_count }})</i>
              {% endif %}
            {% else %}
              <i class="bi bi-emoji-frown">({{ post.dislike_count }})</i>
            {% endif %}
          </a>
        </div>
      </div>
      <!-- Delete, Update buttons -->
      {% if request.user == post.author %}
      <nav class="blog-pagination mt-3 mb-3" aria-label="Pagination">
        <a 
        class="btn btn-outline-danger" 
        href="{% url 'blog:post_delete' post.slug %}"
        hx-get="{% url 'blog:post_delete' post.slug %}"
        hx-push-url="true"
        hx-target="#main-content"
        >delete</a>
        <a 
        class="btn btn-outline-warning" 
        href="{% url 'blog:post_update' post.slug %}"
        hx-get="{% url 'blog:post_update' post.slug %}"
        hx-push-url="true"
        hx-target="#main-content"
        >update</a>
      </nav>
      {% endif %}
      <!-- Send comment message -->
       <div id="post_comments_form">
         <form 
         action="{% url 'blog:post_message' post.slug %}#post_comments_form" 
         hx-get="{% url 'blog:post_message' post.slug %}#post_comments_form" 
         hx-push-url="true"
         hx-target="#main-content"
         class="mt-3 mb-3">
           {% csrf_token %}
           <div class="d-flex">
             <input type="text" name="post_message_input" class="form-control" placeholder="message..." required="">
             <button class="btn btn-outline-success ms-2">Send</button>
           </div>
         </form>
       </div>
      <!-- Post comments -->
      <div id="post_comments">
        <div class="list-group">
          {% for comment in post_comments %}
          <a href="#" class="list-group-item list-group-item-action d-flex gap-3 py-3" aria-current="true">
            <img src="{{ comment.user.get_user_avatar_url }}" alt="twbs" width="32" height="32" class="rounded-circle flex-shrink-0">
            <div class="d-flex gap-2 w-100 justify-content-between">
              <div>
                <h6 class="mb-0">{{ comment.user }}</h6>
                <p class="mb-0 opacity-75">{{ comment.message }}</p>
              </div>
              <small class="opacity-50 text-nowrap">{{ comment.created_at }}</small>
            </div>
          </a>
          {% empty %}
            <center>Now messages</center>
          {% endfor %}
        </div>
      </div>
    </div>
    {% include 'components/latest_posts.html' %}
  </div>
</main>

templates/blog/profile.html
<main role="main" class="container">
    <div class="row">
        <!-- Content -->
        <div class="col-md-4">
            <div class="content-section">
                <center>
                    <img src="{{ user.get_user_avatar_url }}" class="img-fluid"
                        style="border-radius: 50%; width: 200px; height: 200px;" alt="">
                    <h3>
                        {% if user.first_name %}
                        {{ user.first_name }}
                        {% elif user.last_name %}
                        {{ user.last_name }}
                        {% else %}
                        {{ user.username }}
                        {% endif %}
                    </h3>
                    <p class='text-muted'>
                        {{ user.get_user_bio }}
                    <ul class="list-group">
                        <li class="list-group-item list-group-item-light">Latest Posts</li>
                        <li class="list-group-item list-group-item-light">Announcements</li>
                        <li class="list-group-item list-group-item-light">Calendars</li>
                        <li class="list-group-item list-group-item-light">etc</li>
                    </ul>
                    </p>
                </center>
            </div>
        </div>
        <div class="col-md-8">
            <!--  -->
            <div class="d-flex">

                {% if request.user == user %}
                <div class="col">
                    <a 
                    href="{% url 'blog:post_create' %}" 
                    hx-get="{% url 'blog:post_create' %}" 
                    hx-push-url="true"
                    hx-target="#main-content"
                    class="btn btn-outline-secondary">Create New Post</a>
                </div>
                {% endif %}
                <div class="col">
                    <form action="{% url 'users:user_profile' user.username %}">
                        <div class="d-flex">
                            <input class="form-control" type="text" name="search_query_for_user_profile"
                                placeholder="Search" aria-label="Search">
                            <button type="submit" class="btn btn-success ms-2"><i class="bi bi-search"></i></button>
                        </div>
                    </form>
                </div>
            </div>

            {% for post in posts %}
            <div class="col-md-12 mt-3 mb-3">
                <div
                    class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                    <div class="col p-4 d-flex flex-column position-static">
                        
                        <h3 class="mb-0">{{ post.title }}</h3>
                        <div class="mb-1 text-muted">{{ post.publisher_at }}</div>
                        <p class="card-text mb-auto">{{ post.description|truncatewords_html:30  }}</p>
                        <a 
                        href="{{ post.get_absolute_url }}" 
                        hx-get="{{ post.get_absolute_url }}" 
                        hx-push-url="true"
                        hx-target="#main-content"
                        class="stretched-link"
                        >Continue reading</a>
                        <div class="d-flex">
                            <strong class="d-inline-block mb-2 col text-primary"><i class="bi bi-eye">{{ post.watching }}</i></strong>
                            <strong class="d-inline-block mb-2 col text-primary"><i class="bi bi-star">{{ post.like_count }}</i></strong>
                            <strong class="d-inline-block mb-2 col text-primary"><i class="bi bi-chat">{{ post.comment_count }}</i></strong>
                        </div>
                    </div>
                </div>
            </div>
            {% empty %}
            <center>
                Now posts
            </center>
            {% endfor %}
        </div>
    </div>
</main>