apps/blog/urls.py
from django.urls import path
from . import views


app_name = "blog"

urlpatterns = [
    path("", views.HomePageView.as_view(), name="home"),
    path("about/", views.AboutPageView.as_view(), name="about"),
    path("contacts/", views.ContactsPageView.as_view(), name="contacts"),
    path("delete/<slug:slug>", views.PostDeletePageView.as_view(), name="post_delete"),
    path("<slug:slug>", views.PostDetailPageView.as_view(), name="post_detail"),
    path("update/<slug:slug>", views.PostUpdateView.as_view(), name="post_update"),
    path("create/", views.PostCreatePageView.as_view(), name="post_create"),
    path("user/posts/", views.UserPostsPageView.as_view(), name="user_posts"),
    path("like/<slug:slug>", views.post_like, name="post_like"),
    path("dislike/<slug:slug>", views.post_dislike, name="post_dislike"),
    path("message/<slug:slug>", views.post_message, name="post_message"),
    path("settings/", views.SettingsPageView.as_view(), name="user_settings"),
]

apps/users/urls.py
from django.urls import path

from . import views


app_name = "users"

urlpatterns = [
    path("login/", views.LoginPageView.as_view(), name="login"),
    path("register/", views.RegisterPageView.as_view(), name="register"),
    path("logout/", views.LogoutPageView.as_view(), name="logout"),
    path(
        "profile/<str:username>",
        views.UserProfilePageView.as_view(),
        name="user_profile",
    ),
]

core/urls.py
from django.conf.urls import handler400, handler403, handler404, handler500  # noqa
from django.conf.urls.i18n import i18n_patterns  # noqa: F401
from django.conf.urls.static import static
from django.conf import settings

from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.sitemaps.views import sitemap

from apps.blog.sitemaps import PostSitemap
from apps.users.api_endpoints import router as users_api_router
from apps.blog.api_endpoints import router as blog_api_router

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)


sitemaps = {
    "posts": PostSitemap,
}

# URLs
urlpatterns = [
    path("admin/", admin.site.urls),
    path("i18n", include("django.conf.urls.i18n")),
    path("rosetta/", include("rosetta.urls")),
]

# Translated urls
urlpatterns += i18n_patterns(
    path("", include("apps.blog.urls", namespace="blog")),
    path("users/", include("apps.users.urls", namespace="users")),
    path("robots.txt", TemplateView.as_view(template_name="bunin/robots.txt")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
)

# API Endpoints
urlpatterns += [
    path("api/token", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("api/token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("api/v1/users/", include(users_api_router.urls)),
    path("api/v1/blogs/", include(blog_api_router.urls)),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler400 = "apps.shared.views.bad_request_view"  # noqa
handler403 = "apps.shared.views.page_permission_denied_view"  # noqa
handler404 = "apps.shared.views.page_not_found_view"  # noqa
handler500 = "apps.shared.views.server_error_view"  # noqa

templates/components/footers.html
<div class="b-example-divider"></div>
<footer class="py-3 my-4">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Home</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Features</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Pricing</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
    </ul>
    <p class="text-center text-muted">© 2024 Akrom Rustamov, Tashkent</p>
  </footer>

templates/components/headers.html
<nav class="navbar navbar-expand-lg navbar-light bg-light rounded" aria-label="Eleventh navbar example">
    <div class="container-fluid">
      <!-- Site logo -->
      <a 
      class="navbar-brand" 
      href="{% url 'blog:home' %}"
      hx-get="{% url 'blog:home' %}"
      hx-push-url="true"
      hx-target="#main-content"
      ><b>AkromBLOG</b></a>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample09" aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExample09">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <!-- Home -->
            <a 
            class="nav-link active" 
            aria-current="page" 
            href="{% url 'blog:home' %}"
            hx-get="{% url 'blog:home' %}"
            hx-push-url="true"
            hx-target="#main-content"
            >Home</a>
          </li>
          <li class="nav-item">
            <!-- About -->
            <a 
            class="nav-link active" 
            aria-current="page" 
            href="{% url 'blog:about' %}"
            hx-get="{% url 'blog:about' %}"
            hx-push-url="true"
            hx-target="#main-content"
            >About</a>
          </li>
          <li class="nav-item">
            <!-- Contacts -->
            <a 
            class="nav-link active" 
            aria-current="page" 
            href="{% url 'blog:contacts' %}"
            hx-get="{% url 'blog:contacts' %}"
            hx-push-url="true"
            hx-target="#main-content"
            >Contact</a>
          </li>
        </ul>

        <ul class="navbar-nav col-md-3">
          {% if request.user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdown09" data-bs-toggle="dropdown" aria-expanded="false">{{ request.user }}</a>
            <ul class="dropdown-menu" aria-labelledby="dropdown09">
              <!-- Create post -->
              <li><a 
                class="dropdown-item" 
                href="{% url 'blog:post_create' %}"
                hx-get="{% url 'blog:post_create' %}"
                hx-push-url="true"
                hx-target="#main-content"
                >Create</a>
              </li>
              <!-- Profile -->
              <li><a 
                class="dropdown-item" 
                href="{% url 'users:user_profile' request.user.username %}"
                hx-get="{% url 'users:user_profile' request.user.username %}"
                hx-push-url="true"
                hx-target="#main-content"
                >Profile</a>
              </li>
              <!-- User posts -->
              <li><a 
                class="dropdown-item" 
                href="{% url 'blog:user_posts' %}"
                hx-get="{% url 'blog:user_posts' %}"
                hx-push-url="true"
                hx-target="#main-content"
                >My posts</a>
              </li>
              <li><a 
                class="dropdown-item" 
                href="{% url 'blog:user_settings' %}"
                hx-get="{% url 'blog:user_settings' %}"
                hx-push-url="true"
                hx-target="#main-content"
                >Settings</a>
              </li>
              <li><a 
                class="dropdown-item" 
                href="{% url 'users:logout' %}"
                hx-get="{% url 'users:logout' %}"
                hx-push-url="true"
                hx-target="#main-content"
                >Logout</a>
              </li>
            </ul>
          </li>

          {% else %}
          <li class="nav-item">
              <!-- Login page -->
              <a 
              class="nav-link active" 
              aria-current="page" 
              href="{% url 'users:login' %}"
              hx-get="{% url 'users:login' %}"
              hx-push-url="true"
              hx-target="#main-content"
              >Login</a>
          </li>
          <li class="nav-item">
              <!-- Register page -->
              <a 
              class="nav-link active" 
              aria-current="page" 
              href="{% url 'users:register' %}"
              hx-get="{% url 'users:register' %}"
              hx-push-url="true"
              hx-target="#main-content"
              >Register</a>
          </li>
        {% endif %}
        </ul>

        <!-- Search posts -->
        <form 
        action="{% url 'blog:home' %}" 
        hx-get="{% url 'blog:home' %}" 
        hx-push-url="true" 
        hx-target="#main-content">
          <input 
          class="form-control me-2" 
          type="search" 
          name="search_query" 
          id="search-posts" 
          placeholder="Search" 
          value="{% if search_query_value %}{{ search_query_value }}{% endif %}" 
          aria-label="Search"
          hx-get="{% url 'blog:home' %}"
          hx-trigger="keyup changed delay:150ms"
          hx-triget="#main-content"
          >
        </form>
          <div class="d-flex md-2 ms-2">

            <i class="bi bi-search"></i>
          </div>

      </div>
    </div>
  </nav>

templates/components/latest_posts.html
<div class="col-md-4">
    <div class="content-section">
      <h3>Our Sidebar</h3>
      <p class='text-muted'>You can put any information here you'd like.
        <ul class="list-group">
          <li class="list-group-item list-group-item-light">Latest Posts</li>
          <li class="list-group-item list-group-item-light">Announcements</li>
          <li class="list-group-item list-group-item-light">Calendars</li>
          <li class="list-group-item list-group-item-light">etc</li>
        </ul></p>
  </div>
  </div>

templates/components/messages.html
{% if messages %}
    <div id="messages">
    {% for message in messages %}
        {% if message.tags == 'error' %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% else %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endif %}
    {% endfor %}
    </div>
{% endif %}

templates/components/paginators.html
{% if page_obj %}
<div class="d-flex align-items-center justify-content-between">
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            <!-- Кнопка "Назад" -->
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a 
                class="page-link" 
                href="{% url 'blog:home' %}?page={{ page_obj.previous_page_number }}&size={{ size_value }}" 
                hx-get="{% url 'blog:home' %}?page={{ page_obj.previous_page_number }}&size={{ size_value }}" 
                hx-push-url="true"
                hx-target="#main-content"
                aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <span class="page-link">&laquo;</span>
            </li>
            {% endif %}

            <!-- Ссылки на страницы -->
            {% for i in page_obj.paginator.page_range %}
                {% if i == page_obj.number %}
                    <li class="page-item active">
                        <span class="page-link">{{ i }}</span>
                    </li>
                {% elif i >= page_obj.number|add:'-2' and i <= page_obj.number|add:'2' %}
                    <li class="page-item">
                        <a 
                        class="page-link" 
                        href="{% url 'blog:home' %}?page={{ i }}&size={{ size_value }}"
                        hx-get="{% url 'blog:home' %}?page={{ i }}&size={{ size_value }}"
                        hx-push-url="true"
                        hx-target="#main-content"
                        >{{ i }}</a>
                    </li>
                {% elif i == 1 or i == page_obj.paginator.num_pages %}
                    <li class="page-item">
                        <a 
                        class="page-link" 
                        href="{% url 'blog:home' %}?page={{ i }}&size={{ size_value }}"
                        hx-get="{% url 'blog:home' %}?page={{ i }}&size={{ size_value }}"
                        hx-push-url="true"
                        hx-target="#main-content"
                        >{{ i }}</a>
                    </li>
                {% elif i == page_obj.number|add:'-3' or i == page_obj.number|add:'3' %}
                    <li class="page-item disabled"><span class="page-link">...</span></li>
                {% endif %}
            {% endfor %}

            <!-- Кнопка "Вперед" -->
            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" 
                href="{% url 'blog:home' %}?page={{ page_obj.next_page_number }}&size={{ size_value }}" 
                hx-get="{% url 'blog:home' %}?page={{ page_obj.next_page_number }}&size={{ size_value }}" 
                hx-push-url="true"
                hx-target="#main-content"
                aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <span class="page-link">&raquo;</span>
            </li>
            {% endif %}
        </ul>
    </nav>

    <!-- Выбор количества записей на странице -->
    <div class="col-md-2">
        <form action="" method="get" class="d-flex align-items-center">
            <input type="hidden" name="page" value="{{ page_obj.number }}">
            <label for="size" class="me-2">Size:</label>
            <input name="size" type="number" min="1" value="{{ size_value }}" class="form-control" onchange="this.form.submit()">
        </form>
    </div>
</div>
{% endif %}